send_data:
  name: Отправить показания
  description: Отправляет текущие показания сенсоров в сервис Народный мониторинг.

  fields:
    device_id:
      name: Device
      description: The device to send data from.
      required: true
      selector:
        device:
          integration: narodmon_sender
